services:

  usuariosapi-db:
    image: postgres:16
    container_name: usuariosapi-postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: usuariosapi
      POSTGRES_USER: usuariosapi_user
      POSTGRES_PASSWORD: usuariosapi_password
    volumes:
      - usuariosapi-db-data:/var/lib/postgresql/data

  usuariosapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usuariosapi-app
    depends_on:
      - usuariosapi-db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://usuariosapi-db:5432/usuariosapi
      SPRING_DATASOURCE_USERNAME: usuariosapi_user
      SPRING_DATASOURCE_PASSWORD: usuariosapi_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      JWT_SECRET: 37eda45a-0c72-425c-a6c6-e750eefddc27
      JWT_EXPIRATION: 3600000

volumes:
  usuariosapi-db-data:
